/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodj_assignment;

/**
 *
 * @author phili
 */
public class Cus_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Main_Menu
     */
    public Cus_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuAddCustomer = new javax.swing.JMenuItem();
        menuAddProduct = new javax.swing.JMenuItem();
        menuAddOrder = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuEditCustomer = new javax.swing.JMenuItem();
        menuEditProduct = new javax.swing.JMenuItem();
        menuEditOrder = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuViewCustomer = new javax.swing.JMenuItem();
        menuViewProduct = new javax.swing.JMenuItem();
        menuViewOrder = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuDeleteCustomer = new javax.swing.JMenuItem();
        menuDeleteProduct = new javax.swing.JMenuItem();
        menuDeleteOrder = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuSearchCustomer = new javax.swing.JMenuItem();
        menuSearchProduct = new javax.swing.JMenuItem();
        menuSearchOrder = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Add");

        menuAddCustomer.setText("Add Customer");
        jMenu1.add(menuAddCustomer);

        menuAddProduct.setText("Add Product");
        jMenu1.add(menuAddProduct);

        menuAddOrder.setText("Add Order");
        jMenu1.add(menuAddOrder);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        menuEditCustomer.setText("Edit Customer");
        jMenu2.add(menuEditCustomer);

        menuEditProduct.setText("Edit Product");
        jMenu2.add(menuEditProduct);

        menuEditOrder.setText("Edit Order");
        jMenu2.add(menuEditOrder);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("View");

        menuViewCustomer.setText("View Customer");
        jMenu3.add(menuViewCustomer);

        menuViewProduct.setText("View Product");
        jMenu3.add(menuViewProduct);

        menuViewOrder.setText("View Order");
        jMenu3.add(menuViewOrder);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Delete");

        menuDeleteCustomer.setText("Delete Customer");
        jMenu4.add(menuDeleteCustomer);

        menuDeleteProduct.setText("Delete Product");
        jMenu4.add(menuDeleteProduct);

        menuDeleteOrder.setText("Delete Order");
        jMenu4.add(menuDeleteOrder);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Search");

        menuSearchCustomer.setText("Search Customer");
        jMenu5.add(menuSearchCustomer);

        menuSearchProduct.setText("Search Product");
        jMenu5.add(menuSearchProduct);

        menuSearchOrder.setText("Search Order");
        jMenu5.add(menuSearchOrder);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cus_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cus_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cus_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cus_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cus_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAddCustomer;
    private javax.swing.JMenuItem menuAddOrder;
    private javax.swing.JMenuItem menuAddProduct;
    private javax.swing.JMenuItem menuDeleteCustomer;
    private javax.swing.JMenuItem menuDeleteOrder;
    private javax.swing.JMenuItem menuDeleteProduct;
    private javax.swing.JMenuItem menuEditCustomer;
    private javax.swing.JMenuItem menuEditOrder;
    private javax.swing.JMenuItem menuEditProduct;
    private javax.swing.JMenuItem menuSearchCustomer;
    private javax.swing.JMenuItem menuSearchOrder;
    private javax.swing.JMenuItem menuSearchProduct;
    private javax.swing.JMenuItem menuViewCustomer;
    private javax.swing.JMenuItem menuViewOrder;
    private javax.swing.JMenuItem menuViewProduct;
    // End of variables declaration//GEN-END:variables
}
